# Generated by Django 4.0.4 on 2022-05-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0007_newreview_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='mean_rating',
        ),
    ]
